// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH4DFC6oqvGudpn4ak_FmzKoL46aI-uzU',
    appId: '1:478090394339:web:2570ce4db3370dfd6663d6',
    messagingSenderId: '478090394339',
    projectId: 'lampung-xplore1',
    authDomain: 'lampung-xplore1.firebaseapp.com',
    storageBucket: 'lampung-xplore1.appspot.com',
    measurementId: 'G-BKBVPR4843',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsrMgVoRp6OQzTVumfPg4z4PBqbXwFm9Y',
    appId: '1:478090394339:android:29768effa88206be6663d6',
    messagingSenderId: '478090394339',
    projectId: 'lampung-xplore1',
    storageBucket: 'lampung-xplore1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX03_EWmi8zzxtFaGL71Tbk6Jg3yoa2_o',
    appId: '1:478090394339:ios:46d305f63129ba216663d6',
    messagingSenderId: '478090394339',
    projectId: 'lampung-xplore1',
    storageBucket: 'lampung-xplore1.appspot.com',
    iosBundleId: 'com.example.lampungxplore',
  );
}
